code --install-extension adpyke.codesnap
code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension albert.tabout
code --install-extension arcsine.chronicler
code --install-extension austenc.tailwind-docs
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codescene.codescene-vscode
code --install-extension davidanson.vscode-markdownlint
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eliverlara.andromeda
code --install-extension esbenp.prettier-vscode
code --install-extension figma.figma-vscode-extension
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension grapecity.gc-excelviewer
code --install-extension heybourn.headwind
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension jonkwheeler.styled-components-snippets
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension moalamri.inline-fold
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension numso.prettier-standard-vscode
code --install-extension oderwat.indent-rainbow
code --install-extension ritwickdey.liveserver
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension softwaredotcom.swdc-vscode
code --install-extension stormwarning.json-template
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension tonybaloney.vscode-pets
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wallabyjs.console-ninja
code --install-extension wayou.vscode-todo-highlight
code --install-extension xabikos.javascriptsnippets
code --install-extension xabikos.reactsnippets
code --install-extension yzhang.markdown-all-in-one
